### PR TITLE
Hkl v5.0.0.3434 for libhkl v1.2.1

### LINKED ISSUE #11: new ESRF ID01 PSIC geometry
Upsyream [v5.0.0.3381](https://repo.or.cz/hkl.git/commit/742a5f856ae8369256dc8dfadcbeb7b6ed857706) has new geometry: _ESRF ID01 PSIC_

### PR DESCRIPTION
**Pull request by prjemian**
- close #11 

Adds _ESRF ID01 PSIC_ diffractometer geometry.

This is the [latest tagged version](https://repo.or.cz/hkl.git).

### CODE REVIEW

**Comment by prjemian** [comment]
Console output from the _test_ VM (docker container):

```
(base) prjemian@arf:~/.../libhkl/tests$ docker run -it libhkl/test:latest /bin/bash                                                                                                                 
(base) root@88fa139690f5:/home# bash /home/run-libhkl.sh                                                                                                                                            
libhkl.VERSION='v5.0.0.3434'
1	E4CH
2	E4CV
3	E6C
4	ESRF ID01 PSIC
5	K4CV
6	K6C
7	PETRA3 P09 EH2
8	PETRA3 P23 4C
9	PETRA3 P23 6C
10	SOLEIL MARS
11	SOLEIL NANOSCOPIUM ROBOT
12	SOLEIL SIRIUS KAPPA
13	SOLEIL SIRIUS TURRET
14	SOLEIL SIXS MED1+2
15	SOLEIL SIXS MED2+2
16	SOLEIL SIXS MED2+3
17	SOLEIL SIXS MED2+3 v2
18	TwoC
19	ZAXIS
All tests finished successfully.
```

**Review by mrakitin — APPROVED** [review]
Looks good to me!

**Review by padraic-shafer — APPROVED** [review]
No objections.

**Comment by prjemian** [comment]
@padraic-shafer , @mrakitin Thanks!  That was fast!

**Pull request merged**
