### PR TITLE
update build tools

### LINKED ISSUE #10: keep up with the build tools
The upstream library is adding build tools.  Keep up.

- inih (INI Not Invented Here)
- cglm (Highly Optimized 2D / 3D Graphics Math (glm) for C)
- ghc (Glasgow Haskell Compiler)

### PR DESCRIPTION
**Pull request by prjemian**
- close #10

### CODE REVIEW

**Comment by prjemian** [comment]
While working on a new APS-specific diffractometer geometry, I encountered problems building the libhkl library from the current (unmodified) source code.  A particularly cranky problem was re-building the gobject-introspection library from its source.  That should not happen.  There's a local patch removing that problem.  Seems more tools are added (at Soleil) to the compiler chain for libhkl.

**Comment by prjemian** [comment]
I plan to merge these changes on 2024-04-05 unless there are changes.

**Review by mrakitin — COMMENTED** [review]
Looks good to me after a quick skim through.

**Review by mrakitin — APPROVED** [review]

**Comment by prjemian** [comment]
@mrakitin Thanks!  @padraic-shafer - Any comments?

**Pull request merged**
